use_frameworks!

target 'AJLayoutKit_Example' do
  pod 'AJLayoutKit', :path => '../'

  target 'AJLayoutKit_Tests' do
    inherit! :search_paths

    pod 'AJLayoutKit', :path => '../'
#    pod 'Quick', '~> 1.2.0'
#    pod 'Nimble', '~> 7.0.2'
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
